sudo:
  required

services:
  - docker

language: java

jdk:
  - oraclejdk8

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - develop

after_success:

   #LOGIN
  - docker login -u $D_USER -p $D_PASS

   #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "develop" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

   #ENTRY
  - export ENTRY=vadimeladii7/entry
  - docker build -t $ENTRY:$COMMIT ./entry
  - docker tag $ENTRY:$COMMIT $ENTRY:$TAG
  - docker push $ENTRY

   #USERMANAGEMENT
  - export USERMANAGEMENT=vadimeladii7/usermanagement
  - docker build -t $USERMANAGEMENT:$COMMIT ./usermanagement
  - docker tag $USERMANAGEMENT:$COMMIT $USERMANAGEMENT:$TAG
  - docker push $USERMANAGEMENT

   #GATEWAY
  - export GATEWAY=vadimeladii7/gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

   #REGISTRY
  - export REGISTRY=vadimeladii7/registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

   #NOTIFICATION
  - export NOTIFICATION=vadimeladii7/notification
  - docker build -t $NOTIFICATION:$COMMIT ./notification
  - docker tag $NOTIFICATION:$COMMIT $NOTIFICATION:$TAG
  - docker push $NOTIFICATION
