sudo:
  required

services:
  - docker

language: java

jdk:
  - oraclejdk8

os:
  - linux

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

branches:
  only:
    - develop

after_success:
  - docker login -u $D_USER -p $D_PASS
  - export NAME=vadimeladii7/parking
  - docker build -t $NAME:$COMMIT ./entry
  - docker push $NAME

before_script:
- chmod a+x gradlew

script:
- ./entry/gradlew clean build