sudo:
  required

services:
  docker

language: java

jdk:
  - oraclejdk8

os:
  - linux

env:
  global:
    - COMMIT = ${TRAVIS_COMMIT::7}

branches:
  only:
    - develop

after_success:
  - docker login -u $D_USER -p $D_PASS
  - export TAG='if [ "$TRAVIS_BRANCH" === "develop" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi'
  - export NAME = veladii/parking
  - docker build -t $NAME:$COMMIT .
  - docker tag $NAME:$COMMIT $NAME:$TAG
  - docker push $NAME

before_script:
- chmod a+x gradlew

script:
#- ./gradlew clean build
- ./entry/gradlew clean build