#Server Config
server:
  port: 8082

#Spring Cloud Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#Spring Cloud Security OAUTH2
#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:9999/service/user

#Jersey configuration
spring:
  jersey:
    application-path: /api